### ISSUE TITLE
Doesn't work with TB 102.0.3 (64 bits) and cannot be uninstalled

### ISSUE THREAD

**Issue by tauberlise** [dreadnaut/bordercolors-d#31] opened 2022-07-22 21:24 UTC
Hello, 
I installed bordercolors-d, the colors are not saved. 
Since I installed this plugin, I can no more uninstall any extension! 

macOS 12.5
MacBook Pro (13-inch, M1, 2020)

**Comment by dreadnaut** [comment] 2022-07-23 11:27
Ouch, that sounds like a really annoying issue! As with #30 though, I think there's something going on with Thunderbird itself, and upgrading to the new version. As mentioned in the comments for the other issue, could you try with a clean Thunderbird profile?

**Comment by tauberlise** [comment] 2022-07-23 11:57
`I've brought this up on the Add-ons dev mailing list:`
Thanks 😀

**Comment by tauberlise** [comment] 2022-07-23 13:08
It's really a bug in TB! I just installed a new plugin (I had uninstalled bordercolor via the Finder), and I can delete again extension and themes!!
I didn't try yet to reinstall bordercolor 😀

**Comment by dreadnaut** [comment] 2022-07-25 18:15
Hello again 👋 As I mentioned on issue #30, [I've been asked](https://thunderbird.topicbox.com/groups/addons/Tb96796921b4e6fa1/tb-add-on-developers-add-ons-preferences-troubles-with-tb102) for a few more details to help the Thunderbird team debug your issue:
- the last version of Thunderbird where you *did not* have this issue
- which steps did you take while upgrading (e.g., TB68 → 91 → 102, or straight from 68 to 102, or yet a different combination?)
- the first version Thunderbird where you noticed the issue
- do you have a backup of the before-the-issue Thunderbird profile?

Happy to report your answers, or you can join the mailing list yourself —it's easy to leave.

Plus, there's the possibility to have a screen sharing issue with someone in the team, to investigate further.

**Comment by tauberlise** [comment] 2022-07-29 18:55
Hello, 
With the latest version of Thunderbird 102.1.0, BorderColors (Version 2021.9.1) works a little better 😀 
I can save colours for only two accounts, the border options work for both accounts. 
For the other accounts, the message windows are framed with white dotted lines... 

Deleting extensions is now possible... 

Thanks for the follow up 
Lise

**Comment by dreadnaut** [comment] 2022-07-30 10:33
Thanks for the updates! We are digging a bit deeper to see if we can find the cause, so I've prepared a [test version](https://github.com/dreadnaut/bordercolors-d/releases/tag/debug-preferences) that prints some extra information when the add-on tries to save its preferences.

If you have time, could you install it and check under Tools \ Developer Tools \ Error Console for any messages starting with `[BorderColors preferences]`?

**Comment by tauberlise** [comment] 2022-07-30 10:57
OK, I'll test it!

**Comment by fran-f** [comment] 2023-09-05 17:15
Hey @tauberlise, not sure if you solved this issue or gave up 😅  Let me know if you still need help, or if I can close this.

**Comment by dreadnaut** [comment] 2023-09-05 17:16
Hey tauberlise, not sure if you solved this issue or gave up 😅 Let me know if you still need help, or if I can close this.

**Closed** 2023-09-18 15:42 UTC
